### ISSUE TITLE
My capture doesnt work

### ISSUE THREAD

**Issue by TonCZ** [eliemichel/MapsModelsImporter-samples#2]
Hi, so i´ve tried my own capture by following an youtube tutorial, however, it doesnt work for me. I tried your samples and those worked.
http://www.mediafire.com/file/15tcwc5cdx0amax/canyon.rdc/file here is the file that doesnt work

**Comment by eliemichel** [comment]
Seems that you're using RenderDoc v1.11, which is not supported yet. Use v1.10 instead!

**Comment by TonCZ** [comment]
Ohh thank you! Ill try it
